name: Build Plugin ZIP

on:
  release:
    types: [published]

jobs:
  build-zip:
    name: Build and upload plugin zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create plugin folder
        run: |
          mkdir campaignium-hosting
          shopt -s extglob
          mv !(campaignium-hosting) campaignium-hosting/

      - name: Zip plugin
        run: zip -r campaignium-hosting.zip campaignium-hosting

      - name: Upload plugin zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./campaignium-hosting.zip
          asset_name: campaignium-hosting.zip
          asset_content_type: application/zip

