name: Build Plugin ZIP

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-zip:
    name: Build and upload plugin zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create plugin folder
        run: |
          mkdir campaignium-hosting
          rsync -av --exclude=campaignium-hosting --exclude=.git --exclude=.github ./ campaignium-hosting/

      - name: Zip plugin
        run: zip -r campaignium-hosting.zip campaignium-hosting

      - name: Upload plugin zip (PUBLICLY ACCESSIBLE!)
        uses: softprops/action-gh-release@v1
        with:
          files: campaignium-hosting.zip
          token: ${{ secrets.GH_PAT }}
          asset_content_type: application/zip
